#! /bin/bash

sudo rm -r /var/www/html/voco-book/
sudo mkdir /var/www/html/voco-book/
sudo cp -r lib/* /var/www/html/voco-book/
sudo chown -R www-data:www-data /var/www/html/voco-book

sudo rm /etc/php/7.4/apache2/php.ini
sudo cp lib/conf/php-ORIGINAL.ini /etc/php/7.4/apache2/php.ini
sudo /etc/init.d/apache2 restart
