#!/bin/sh
mktexlsr
tlmgr init-usertree
tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
#tlmgr install zapfding
#tlmgr install collection-latexrecommended
#tlmgr install collection-fontsrecommended
